services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./nginx_conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx_conf/nginx.conf:/etc/nginx/nginx.conf

  db:
    container_name: db
    image: postgres:14-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  pgbouncer:
    container_name: pgbouncer
    image: edoburu/pgbouncer:v1.24.1-p1
    restart: always
    depends_on:
      - db
    ports:
      - "6432:6432"
    volumes:
      - ./pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini:ro
      - ./pgbouncer/users.txt:/etc/pgbouncer/users.txt:ro
    environment:
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      POOL_MODE: transaction
      
  migrate:
    build: .
    command: bash -lc 'alembic upgrade head'
    environment:
      DATABASE_URL: postgresql+psycopg://pgres:pgres@pgbouncer:6432/pgres
      SYNC_DATABASE_URL: postgresql+psycopg://pgres:pgres@pgbouncer:6432/pgres
    depends_on:
      - pgbouncer
    restart: "no"

  app:
    build: .
    restart: always
    deploy:
      replicas: 3
    command:
        - bash
        - -lc
        - |
          exec gunicorn src.main_app.init_app:app \
            -k uvicorn.workers.UvicornWorker \
            --workers 8 \
            --bind 0.0.0.0:8001 \
            --backlog 2048 \
            --keep-alive 5
    environment:
      DATABASE_URL: postgresql+psycopg://pgres:pgres@pgbouncer:6432/pgres
      SYNC_DATABASE_URL: postgresql+psycopg://pgres:pgres@pgbouncer:6432/pgres
      DEBUG: "True"
    expose:
      - "8001"
    depends_on:
      - pgbouncer
volumes:
  postgres_data:
